spring:
  datasource:
    url: jdbc:mysql://211.87.229.20:3306/meeting
#    url: jdbc:mysql://127.0.0.1:3306/meeting
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 200MB
      location: C://Files/
      max-request-size: 200MB
server:
   port: 8081

mybatis:
  mapper-locations: "classpath:/mapper/*.xml"
  configuration:
    map-underscore-to-camel-case: true